---
hosts:
    hostname: 10.70.138.109
    username: admin
    password: 1234Qwer
    platform: nxos
    #groups: 
    #  - 'nxos'

hosts2:
    hostname: 10.70.138.110
    username: admin
    password: 1234Qwer
    platform: nxos
    #groups: 
    #  - 'nxos'
